Change Kernel To Anomaly-Kernel

diff --git a/.github/workflows/build_kernel_kebab_nameless15_a15.yml b/.github/workflows/build_kernel_kebab_nameless15_a15.yml
--- a/.github/workflows/build_kernel_kebab_nameless15_a15.yml
+++ b/.github/workflows/build_kernel_kebab_nameless15_a15.yml
@@ -1,4 +1,4 @@
-name: Build Kernel Redmi Note4X (Based-AOSP A13) with KSU and SUSFS
+name: Build Kernel OnePlus 8 (Nameless 15) with KSU and SUSFS
 on:
   workflow_call:
   workflow_dispatch:
@@ -15,7 +15,7 @@ jobs:
       - uses: actions/checkout@v4
       - name: Prepare Configuration
         run: |
-          CONFIG_ENV=$(grep -w "CONFIG_ENV" Profiles/mido_aosp_a13.env | head -n 1 | cut -d "=" -f 2)
+          CONFIG_ENV=$(grep -w "CONFIG_ENV" Profiles/kebab_nameless_a15.env | head -n 1 | cut -d "=" -f 2)
           CONFIG_LIST=(
               DEVICE_NAME
               DEVICE_CODENAME
@@ -38,10 +38,11 @@ jobs:
               SUSFS_FIXED
               AK3_SOURCE
               AK3_BRANCH
+              BOOT_SOURCE
+              LXC_ENABLE
               ROM_TEXT
 
           )
-          ls -al ./
 
           for CONFIG in "${CONFIG_LIST[@]}"; do
               if [[ "$CONFIG" == "EXTRA_CMDS" || "$CONFIG" == "CUSTOM_CMDS" ]]; then
@@ -51,10 +52,31 @@ jobs:
               fi
           done
 
+          # Move patch folder to tmp
+          mv $GITHUB_WORKSPACE/Patches /tmp/
+
+      - name: Free Disk Space (Ubuntu)
+        if: env.LXC_ENABLE == 'true'
+        uses: jlumbroso/free-disk-space@main
+        with:
+          # this might remove tools that are actually needed,
+          # if set to "true" but frees about 6 GB
+          tool-cache: true
+
+          # all of these default to true, but feel free to set to
+          # "false" if necessary for your workflow
+          android: false
+          dotnet: true
+          haskell: true
+          large-packages: true
+          docker-images: true
+          swap-storage: true
+
       - name: Maximize build space
+        if: env.LXC_ENABLE != 'true'
         uses: easimon/maximize-build-space@master
         with:
-          root-reserve-mb: 8192
+          root-reserve-mb: 20480
           temp-reserve-mb: 4096
           swap-size-mb: 8192
           remove-dotnet: "true"
@@ -76,69 +98,82 @@ jobs:
             sudo apt-get install zstd libc6 binutils libc6-dev-i386 gcc g++ p7zip p7zip-full -y
           fi
 
+      - name: Install GNU GCC
+        run: |
+          sudo apt-get install binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi -y
+          echo "GCC_64=CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
+          echo "GCC_32=CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> $GITHUB_ENV
+
       - name: Set Compile Environment
         run: |
           cd $GITHUB_WORKSPACE
 
           # Set GCC Aarch64
-          if [[ ${{ env.GCC_64_SOURCE }} =~ git ]]; then
-            git clone ${{ env.GCC_64_SOURCE }} -b ${{ env.GCC_64_BRANCH }} gcc-64 --depth=1
-            export GCC_64_BIN=aarch64-linux-android-
+          if [ -z "${{ env.GCC_64_SOURCE }}" ]; then
+            echo "Not set GCC 64!"
+          else
+            if [[ "${{ env.GCC_64_SOURCE }}" == *".git" ]]; then
+              git clone ${{ env.GCC_64_SOURCE }} -b ${{ env.GCC_64_BRANCH }} gcc-64 --depth=1
+            fi
+            if [[ "${{ env.GCC_64_SOURCE }}" == *'.tar.gz' ]]; then
+              wget -O gcc-64.tar.gz ${{ env.GCC_64_SOURCE }}
+              mkdir gcc-64
+              tar -C gcc-64/ -zxvf gcc-64.tar.gz
+            fi
+            if [[ "${{ env.GCC_64_SOURCE }}" == *'.zip' ]]; then
+              wget -O gcc-64.zip ${{ env.GCC_64_SOURCE }}
+              mkdir gcc-64
+              unzip gcc-64.zip -d gcc-64/
+            fi
+            GCC_64_BIN=aarch64-linux-android-
+            echo "GCC_64=CROSS_COMPILE=$GITHUB_WORKSPACE/gcc-64/bin/$GCC_64_BIN" >> $GITHUB_ENV
           fi
-          if [[ ${{ env.GCC_64_SOURCE }} == *'.tar.gz' ]]; then
-            wget -O gcc-64.tar.gz ${{ env.GCC_64_SOURCE }}
-            mkdir gcc-64
-            tar -C gcc-64/ -zxvf gcc-64.tar.gz
-            export GCC_64_BIN=aarch64-linux-android-
-          fi
-          if [[ ${{ env.GCC_64_SOURCE }} == *'.zip' ]]; then
-            wget -O gcc-64.zip ${{ env.GCC_64_SOURCE }}
-            mkdir gcc-64
-            unzip gcc-64.zip -d gcc-64/
-            export GCC_64_BIN=aarch64-linux-android-
-          fi
-          echo "GCC_64=CROSS_COMPILE=$GITHUB_WORKSPACE/gcc-64/bin/$GCC_64_BIN" >> $GITHUB_ENV
+
 
           # Set GCC ARM32
-          if [[ ${{ env.GCC_32_SOURCE }} =~ git ]]; then
-            git clone ${{ env.GCC_32_SOURCE }} -b ${{ env.GCC_32_BRANCH }} gcc-32 --depth=1
-            export GCC_32_BIN=arm-linux-androideabi-
+          if [ -z "${{ env.GCC_32_SOURCE }}" ]; then
+            echo "Not set GCC 32!"
+          else
+            if [[ "${{ env.GCC_32_SOURCE }}" == *".git" ]]; then
+              git clone ${{ env.GCC_32_SOURCE }} -b ${{ env.GCC_32_BRANCH }} gcc-32 --depth=1
+            fi
+            if [[ "${{ env.GCC_32_SOURCE }}" == *'.tar.gz' ]]; then
+              wget -O gcc-32.tar.gz ${{ env.GCC_32_SOURCE }}
+              mkdir gcc-32
+              tar -C gcc-32/ -zxvf gcc-32.tar.gz
+            fi
+            if [[ "${{ env.GCC_32_SOURCE }}" == *'.zip' ]]; then
+              wget -O gcc-32.zip ${{ env.GCC_32_SOURCE }}
+              mkdir gcc-32
+              unzip gcc-32.zip -d gcc-32/
+            fi
+            GCC_32_BIN=arm-linux-androideabi-
+            echo "GCC_32=CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/gcc-32/bin/$GCC_32_BIN" >> $GITHUB_ENV
           fi
-          if [[ ${{ env.GCC_32_SOURCE }} == *'.tar.gz' ]]; then
-            wget -O gcc-32.tar.gz ${{ env.GCC_32_SOURCE }}
-            mkdir gcc-32
-            tar -C gcc-32/ -zxvf gcc-32.tar.gz
-            export GCC_32_BIN=arm-linux-androideabi-
-          fi
-          if [[ ${{ env.GCC_32_SOURCE }} == *'.zip' ]]; then
-            wget -O gcc-32.zip ${{ env.GCC_32_SOURCE }}
-            mkdir gcc-32
-            unzip gcc-32.zip -d gcc-32/
-            export GCC_32_BIN=arm-linux-androideabi-
-          fi
-          echo "GCC_32=CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/gcc-32/bin/$GCC_32_BIN" >> $GITHUB_ENV
 
           # Set Clang
-          if [[ ${{ env.CLANG_SOURCE }} =~ git ]]; then
+          if [[ "${{ env.CLANG_SOURCE }}" == *".git" ]]; then
             git clone ${{ env.CLANG_SOURCE }} -b ${{ env.CLANG_BRANCH }} clang-custom --depth=1
-          elif [[ ${{ env.CLANG_SOURCE }} == *'.tar.gz' ]]; then
+          elif [[ "${{ env.CLANG_SOURCE }}" == *'.tar.gz' ]]; then
             wget -O clang.tar.gz ${{ env.CLANG_SOURCE }}
             mkdir clang-custom
             tar -C clang-custom/ -zxvf clang.tar.gz
-          elif [[ ${{ env.CLANG_SOURCE }} == *'.tar.xz' ]]; then
+          elif [[ "${{ env.CLANG_SOURCE }}" == *'.tar.xz' ]]; then
             wget -O clang.tar.xz ${{ env.CLANG_SOURCE }}
             mkdir clang-custom
             tar -C clang-custom/ -xvf clang.tar.xz --strip-components 1
-          elif [[ ${{ env.CLANG_SOURCE }} == *'.zip' ]]; then
+          elif [[ "${{ env.CLANG_SOURCE }}" == *'.zip' ]]; then
             wget -O clang.zip ${{ env.CLANG_SOURCE }}
             mkdir clang-custom
             unzip clang.zip -d clang-custom/
-          elif [[ ${{ env.CLANG_SOURCE }} =~ antman ]]; then
+          elif [[ "${{ env.CLANG_SOURCE }}" == *"antman" ]]; then
             mkdir clang-custom
             cd clang-custom
             wget ${{ env.CLANG_SOURCE }} -O antman
             chmod +x antman
             bash antman -S
+          else
+            echo "Not supported format of Clang!"
           fi
 
       - name: Get Kernel Source
@@ -154,7 +189,7 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE/device_kernel
           echo "CONFIG_KSU=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-          if [[ ${{ env.SUSFS_ENABLE }} == "true" ]]; then
+          if [[ "${{ env.SUSFS_ENABLE }}" == "true" ]]; then
             echo "CONFIG_KSU_SUSFS=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
             echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
             echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
@@ -177,21 +212,22 @@ jobs:
           # Variable
           SUSFS_SOURCE=https://gitlab.com/simonpunk/susfs4ksu.git
           SUSFS_BRANCH=kernel-${{ env.KERNEL_VERSION }}
-          KERNEL_PATCHES=https://github.com/JackA1ltman/NonGKI_Kernel_Patches.git
-          PACK_METHOD=Anykernel3 # Anykernel3 need SOURCE and BRANCH,but MKBOOTIMG needn't it.
+          PACK_METHOD=Anykernel3 # Anykernel3 need SOURCE and BRANCH, MKBOOTIMG needn't it.
           KERNELSU_METHOD=shell # shell and manual
 
           # Set $PACK_METHOD and KernelSU
-          cd $GITHUB_WORKSPACE/device_kernel
           if [[ $PACK_METHOD == "Anykernel3" ]]; then
+            cd $GITHUB_WORKSPACE/device_kernel
             if [[ -d "Anykernel3" ]]; then
               echo "Found Anykernel3 in Kernel!"
             else
               git clone ${{ env.AK3_SOURCE }} -b ${{ env.AK3_BRANCH }} Anykernel3 --depth=1
             fi
           elif [[ $PACK_METHOD == "MKBOOTIMG" ]]; then
-            git clone https://android.googlesource.com/platform/system/tools/mkbootimg $GITHUB_WORKSPACE/mkboottools -b master-kernel-build-2022 --depth=1
+            cd $GITHUB_WORKSPACE
+            git clone https://android.googlesource.com/platform/system/tools/mkbootimg $GITHUB_WORKSPACE/mkboottools -b main-kernel-build-2024 --depth=1
             wget ${{ env.BOOT_SOURCE }} -O $GITHUB_WORKSPACE/boot_source_${{ env.DEVICE_NAME }}.img
+            cd device_kernel
           else
             exit
           fi
@@ -214,41 +250,117 @@ jobs:
           echo "UPLOADNAME=-${{ env.KERNELSU_NAME }}_$KSU_VERSION" >> $GITHUB_ENV
 
           # Set SUSFS
-          git clone $SUSFS_SOURCE -b $SUSFS_BRANCH susfs4ksu --depth=1
-          git clone $KERNEL_PATCHES -b mi_kernel NonGKI_Kernel_Patches --depth=1 # It's not necessary.
-          cp susfs4ksu/kernel_patches/fs/* fs/
-          cp susfs4ksu/kernel_patches/include/linux/* include/linux/
+          if [[ "${{ env.SUSFS_ENABLE }}" == true ]]; then
+            if [[ "${{ env.SUSFS_FIXED }}" == true ]]; then
+              PATCHES_SOURCE=JackA1ltman/NonGKI_Kernel_Patches
+              PATCHES_BRANCH=op_kernel
+              git clone https://github.com/$PATCHES_SOURCE.git -b $PATCHES_BRANCH NonGKI_Kernel_Patches --depth=1 # It's not necessary.
+            fi
+            git clone $SUSFS_SOURCE -b $SUSFS_BRANCH susfs4ksu --depth=1
+            cp susfs4ksu/kernel_patches/fs/* fs/
+            cp susfs4ksu/kernel_patches/include/linux/* include/linux/
+          else
+            echo "Disabled SUSFS !"
+          fi
+
+      - name: Patch Kernel for no-kprobe
+        run: |
+          cd $GITHUB_WORKSPACE
+          KERNEL=$(echo "${{ env.KERNEL_VERSION }}" | awk -F '.' '{print $1}')
+          PATCHLEVEL=$(echo "${{ env.KERNEL_VERSION }}" | awk -F '.' '{print $2}')
+
+          if [[ -f "/tmp/Patches/patches.sh" ]]; then
+            cp /tmp/Patches/patches.sh device_kernel/
+            cd device_kernel
+            bash patches.sh
+            if [ $KERNEL -lt 5 ] && [ $PATCHLEVEL -lt 14 ]; then
+                cp /tmp/Patches/extra_patches.sh device_kernel/
+                cd device_kernel
+                bash extra_patches.sh
+            else
+                echo "your kernel needn't the patch."
+            fi
+          else
+            echo "Cannot found patches.sh in build project , please check u file existed in build project !"
+          fi
 
       - name: Extra Kernel Options
         run: |
           # Only ${{ env.DEVICE_NAME }} use it.
           cd $GITHUB_WORKSPACE/device_kernel
-          echo "CONFIG_CPU_BIG_ENDIAN=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-          echo "CONFIG_COMPAT_VDSO=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_KASAN_STACK_ENABLE=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
           echo "CONFIG_LTO_NONE=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-          echo "CONFIG_INIT_STACK_NONE=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_SHADOW_CALL_STACKE=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_BUILD_ARM64_KERNEL_COMPRESSION_GZIP=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_BUILD_ARM64_DT_OVERLAY=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_BUILD_ARM64_APPENDED_DTB_IMAGE=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo 'CONFIG_BUILD_ARM64_APPENDED_DTB_IMAGE_NAMES=""' >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          sed -i 's/^CONFIG_BUILD_ARM64_UNCOMPRESSED_KERNEL=y$/# CONFIG_BUILD_ARM64_UNCOMPRESSED_KERNEL is not set/' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
           sed -i 's/# CONFIG_SECCOMP is not set/CONFIG_SECCOMP=y/' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
 
-      - name: Patch Kernel for no-kprobe
+      - name: Setup LXC
+        if: env.LXC_ENABLE == 'true'
         run: |
           cd $GITHUB_WORKSPACE/device_kernel
-          if [[ -d "NonGKI_Kernel_Patches" ]]; then
-            echo "Folder existed."
-          else
-            git clone https://github.com/JackA1ltman/NonGKI_Kernel_Patches.git -b mi_kernel NonGKI_Kernel_Patches
+          rm -rf lxc
+          git clone https://github.com/tomxi1997/lxc-docker-support-for-android.git lxc
+          echo 'source "lxc/Kconfig"' >> "Kconfig"
+
+          echo "CONFIG_DOCKER=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+
+          sed -i '/CONFIG_ANDROID_PARANOID_NETWORK/d' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "# CONFIG_ANDROID_PARANOID_NETWORK is not set" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+
+          #sed -i '/CONFIG_LOCALVERSION/d' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          #echo 'CONFIG_LOCALVERSION="-LXC"' >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+
+          chmod +x $GITHUB_WORKSPACE/device_kernel/lxc/runcpatch.sh
+          if [ -f $GITHUB_WORKSPACE/device_kernel/kernel/cgroup/cgroup.c ]; then
+              sh $GITHUB_WORKSPACE/device_kernel/lxc/runcpatch.sh $GITHUB_WORKSPACE/device_kernel/kernel/cgroup/cgroup.c
           fi
 
-          cp NonGKI_Kernel_Patches/patches.sh ./
+          if [ -f $GITHUB_WORKSPACE/device_kernel/kernel/cgroup.c ]; then
+              sh $GITHUB_WORKSPACE/device_kernel/lxc/runcpatch.sh $GITHUB_WORKSPACE/device_kernel/kernel/cgroup.c
+          fi
 
-          bash patches.sh
+          if [ -f $GITHUB_WORKSPACE/device_kernel/net/netfilter/xt_qtaguid.c ]; then
+              patch -p0 < $GITHUB_WORKSPACE/device_kernel/lxc/xt_qtaguid.patch
+          fi
+
+          echo "LXC_ENABLE=lxc" >> $GITHUB_ENV
+
+      - name: Patch Kernel of SUSFS
+        if: env.SUSFS_ENABLE == 'true'
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel/
+          cp susfs4ksu/kernel_patches/50_add_susfs_in_kernel-$KERNEL_VERSION.patch ./
+
+          patch -p1 < 50_add_susfs_in_kernel-${{ env.KERNEL_VERSION }}.patch || true
+
+          if [[ ${{ env.KERNELSU_NAME }}  == "KernelSU-Next" ]]; then
+            if [[ ${{ env.KERNELSU_SOURCE }} =~ ".sh" && ${{ env.KERNELSU_BRANCH }} != *"susfs" ]]; then
+                git clone https://github.com/KernelSU-Next/KernelSU-Next.git -b ${{ env.KERNELSU_BRANCH }}-susfs susfs_fixed
+            elif [[ ${{ env.KERNELSU_BRANCH }} != *"susfs" ]]; then
+                git clone ${{ env.KERNELSU_SOURCE }} -b ${{ env.KERNELSU_BRANCH }}-susfs susfs_fixed
+            fi
+            rsync -av --exclude='.git' susfs_fixed/kernel/ KernelSU-Next/kernel/
+          elif [[ ${{ env.KERNELSU_BRANCH }} != *"susfs" ]]; then
+            cp susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./${{ env.KERNELSU_NAME }}
+            cd ${{ env.KERNELSU_NAME }}
+            patch -p1 < 10_enable_susfs_for_ksu.patch || true
+          fi
 
       - name: Fixed Kernel Patch
         if: env.SUSFS_ENABLE == 'true' && env.SUSFS_FIXED == 'true'
         run: |
           cd $GITHUB_WORKSPACE/device_kernel/
-          cp NonGKI_Kernel_Patches/note4x_aosp_a13/mido_fixed.patch ./
+          cp NonGKI_Kernel_Patches/kona_oos/namespace_fixed.patch ./
+          cp NonGKI_Kernel_Patches/kona_oos/task_mmu_fixed.patch ./
+          cp NonGKI_Kernel_Patches/kona_oos/ksu_backport.patch ./
 
-          patch -p1 < mido_fixed.patch || true
+          patch -p1 < namespace_fixed.patch || true
+          patch -p1 < task_mmu_fixed.patch || true
+          patch -p1 < ksu_backport.patch || true
 
       - name: Setup ccache
         uses: hendrikmuhs/ccache-action@v1.2
@@ -260,7 +372,7 @@ jobs:
         run: |
           export PATH=$GITHUB_WORKSPACE/clang-custom/bin:$PATH
           cd $GITHUB_WORKSPACE/device_kernel/
-          if [[ -z ${{ env.GCC_32 }} && -z ${{ env.GCC_64 }} ]]; then
+          if [ -z "${{ env.GCC_32 }}" ] && [ -z "${{ env.GCC_64 }}" ]; then
             make CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.DEFCONFIG_NAME }}
             make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }}
           else
@@ -317,10 +429,10 @@ jobs:
           cd tmp
           7za a -mx9 tmp.zip *
           cd ..
-          cp -fp tmp/tmp.zip ${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-${{ env.PACK_METHOD }}.zip
+          cp -fp tmp/tmp.zip ${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-${{ env.PACK_METHOD }}${{ env.LXC_STATUS }}.zip
           rm -rf tmp
 
-          echo "PACK_NAME=${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-${{ env.PACK_METHOD }}.zip" >> $GITHUB_ENV
+          echo "PACK_NAME=${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-${{ env.PACK_METHOD }}${{ env.LXC_STATUS }}.zip" >> $GITHUB_ENV
 
       - name: Make Latest Boot Image
         if: env.PACK_METHOD == 'MKBOOTIMG'
@@ -328,12 +440,28 @@ jobs:
           cd $GITHUB_WORKSPACE/
           IMAGE_DIR="$GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot"
           TIME=$(date +"%Y%m%d%H%M%S")
+          FORMAT_MKBOOTING=$(echo `mkboottools/unpack_bootimg.py --boot_img=boot_source_${{ env.DEVICE_NAME }}.img --format mkbootimg`)
 
-          mkboottools/unpack_bootimg.py --boot_img $GITHUB_WORKSPACE/boot_source_${{ env.DEVICE_NAME }}.img
-          cp $IMAGE_DIR/Image.gz-dtb out/kernel
-          mkboottools/mkbootimg.py ${{ env.FORMAT_MKBOOTING }} -o ${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-image.img
+          mkboottools/unpack_bootimg.py --boot_img boot_source_${{ env.DEVICE_NAME }}.img
 
-          echo "PACK_NAME=${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-image.img" >> $GITHUB_ENV
+          if [[ -f "$IMAGE_DIR/Image.gz-dtb" ]]; then
+            rm -f out/kernel
+            cp -fp $IMAGE_DIR/Image.gz-dtb out/kernel
+            echo "Found Image.gz-dtb !"
+          elif [[ -f "$IMAGE_DIR/Image.gz" ]]; then
+            rm -f out/kernel
+            cp -fp $IMAGE_DIR/Image.gz out/kernel
+            echo "Found Image.gz !"
+          elif [[ -f "$IMAGE_DIR/Image" ]]; then
+            rm -f out/kernel
+            gzip -c $IMAGE_DIR/Image > $IMAGE_DIR/Image.gz
+            cp -fp $IMAGE_DIR/Image.gz out/kernel
+            echo "Found Image ! Automatic convert Image.gz ! "
+          fi
+
+          eval "mkboottools/mkbootimg.py $FORMAT_MKBOOTING -o ${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-image${{ env.LXC_STATUS }}.img"
+
+          echo "PACK_NAME=${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-image${{ env.LXC_STATUS }}.img" >> $GITHUB_ENV
 
           rm -f $GITHUB_WORKSPACE/boot_source_${{ env.DEVICE_NAME }}.img
 
